# ConfigureFile.cmake - Substitute @VAR@ variables in a template file
# Usage: cmake -DINPUT_FILE=<in> -DOUTPUT_FILE=<out> -P ConfigureFile.cmake

file(READ "${INPUT_FILE}" FILE_CONTENT)

# Get version and app info from VERSION.txt if not provided
if(NOT DEFINED VERSION)
  file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../VERSION.txt" VERSION_LINES)
  foreach(LINE ${VERSION_LINES})
    if(LINE MATCHES "^([A-Z_]+)=(.*)$")
      set(${CMAKE_MATCH_1} "${CMAKE_MATCH_2}")
    endif()
  endforeach()
  
  # Strip whitespace from all variables
  foreach(VAR VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NAME 
          RELEASE_DATE APP_NAME APP_DISPLAY_NAME APP_EXECUTABLE APP_DESCRIPTION 
          APP_COMPANY APP_COPYRIGHT APP_BUNDLE_ID APP_BUNDLE_NAME APP_ICON_NAME 
          APP_DESKTOP_CATEGORIES EXTENSION_UUID EXTENSION_NAME EXTENSION_DESCRIPTION)
    if(DEFINED ${VAR})
      string(STRIP "${${VAR}}" ${VAR})
    endif()
  endforeach()
endif()

# Substitute all @VAR@ placeholders
foreach(VAR VERSION VERSION_MAJOR VERSION_MINOR VERSION_PATCH VERSION_NAME 
        RELEASE_DATE APP_NAME APP_DISPLAY_NAME APP_EXECUTABLE APP_DESCRIPTION 
        APP_COMPANY APP_COPYRIGHT APP_BUNDLE_ID APP_BUNDLE_NAME APP_ICON_NAME 
        APP_DESKTOP_CATEGORIES EXTENSION_UUID EXTENSION_NAME EXTENSION_DESCRIPTION)
  if(DEFINED ${VAR})
    string(REPLACE "@${VAR}@" "${${VAR}}" FILE_CONTENT "${FILE_CONTENT}")
  endif()
endforeach()

file(WRITE "${OUTPUT_FILE}" "${FILE_CONTENT}")
