function(load_version FILE)
  file(STRINGS "${FILE}" VERSION_LINES)

  foreach(LINE ${VERSION_LINES})
    if(LINE MATCHES "^VERSION=(.*)$")
      set(VERSION "${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(LINE MATCHES "^VERSION_MAJOR=(.*)$")
      set(VERSION_MAJOR "${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(LINE MATCHES "^VERSION_MINOR=(.*)$")
      set(VERSION_MINOR "${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(LINE MATCHES "^VERSION_PATCH=(.*)$")
      set(VERSION_PATCH "${CMAKE_MATCH_1}" PARENT_SCOPE)
    elseif(LINE MATCHES "^RELEASE_DATE=(.*)$")
      set(RELEASE_DATE "${CMAKE_MATCH_1}" PARENT_SCOPE)
    endif()
  endforeach()
endfunction()

set(PROJECT_VERSION ${VERSION})