name: Build debug

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build on ${{ matrix.platform.host }}
    runs-on: ${{ matrix.platform.name }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ubuntu-22.04
            host: linux
            qt_arch: linux_gcc_64
            qt_install_name: gcc_64
          - name: windows-latest
            host: windows
            qt_arch: win64_mingw
            qt_tools: tools_mingw1310
            qt_install_name: mingw_64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
 
      - name: Install build dependencies
        if: matrix.platform.host == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-cursor0 libarchive-dev libwayland-dev wayland-protocols ccache zip

      - name: Install Qt6
        uses: jdpurcell/install-qt-action@v5
        with:
          version: "6.8.2"
          host: ${{ matrix.platform.host }}
          target: "desktop"
          arch: ${{ matrix.platform.qt_arch }}
          modules: "qtmultimedia"
          tools: ${{ matrix.platform.qt_tools || '' }}
          cache: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.platform.host }}-qt6-debug
          max-size: 800M

      - name: Build with CMake
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=RelWithDebInfo \
            -D CMAKE_PREFIX_PATH="${{ runner.workspace }}/Qt/6.8.2/${{ matrix.platform.qt_install_name }}" \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache \
            -D SHIJIMA_WITH_LIBSHIMEJIFINDER=ON
          cmake --build build -j 4

      - name: Archive ${{ matrix.platform.host }} x86_64 debug build
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.platform.host }}-x86_64
          path: build/bin/
          retention-days: 1
