name: Build debug

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build on ${{ matrix.platform.host }}
    runs-on: ${{ matrix.platform.name }}
    env:
      QT_VERSION: "6.8.3"
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: ubuntu-22.04
            host: linux
            qt_arch: linux_gcc_64
            qt_install_name: gcc_64
          - name: windows-latest
            host: windows
            qt_tools: tools_mingw1310
            qt_arch: win64_mingw
            qt_install_name: mingw_64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
 
      - name: Install build dependencies
        if: matrix.platform.host == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-cursor0 libarchive-dev libwayland-dev wayland-protocols ccache zip

      # - name: Patch libshijima & libshimejifinder for MSVC compatibility
      #   if: matrix.platform.host == 'windows'
      #   shell: bash
      #   run: |
      #     sed -i 's/set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Wpedantic")//' libshijima/CMakeLists.txt
      #     sed -i 's/#include <unistd.h>//' libshimejifinder/shimejifinder/archive.cc

      - name: Install Qt6
        uses: jdpurcell/install-qt-action@v5
        with:
          version: ${{ env.QT_VERSION }}
          host: ${{ matrix.platform.host }}
          target: "desktop"
          arch: ${{ matrix.platform.qt_arch }}
          modules: "qtmultimedia"
          tools: ${{ matrix.platform.qt_tools || '' }}
          cache: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.platform.host }}-qt6-debug
          max-size: 500M

      - name: Configure with CMake
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Debug \
            -D CMAKE_PREFIX_PATH="${{ runner.workspace }}/Qt/${{ env.QT_VERSION }}/${{ matrix.platform.qt_install_name }}" \
            -D CMAKE_C_COMPILER_LAUNCHER=ccache \
            -D CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build with CMake
        shell: bash
        run: |
          cmake --build build --parallel --config Debug

      - name: Archive ${{ matrix.platform.host }} x86_64 debug build
        uses: actions/upload-artifact@v4
        with:
          name: debug-${{ matrix.platform.host }}-x86_64
          path: build/bin/
          retention-days: 1
